export enum OrderStatus {
  IN_WAREHOUSE = "IN_WAREHOUSE",
  IN_TRANSIT = "IN_TRANSIT",
  IN_UB = "IN_UB",
  OUT_FOR_DELIVERY = "OUT_FOR_DELIVERY",
  DELIVERED = "DELIVERED",
  CANCELLED = "CANCELLED",
}

export enum OrderSize {
  LARGE = "LARGE",
  MEDIUM = "MEDIUM",
  SMALL = "SMALL",
  UNDEFINED = "UNDEFINED",
}

export enum ROLES {
  ADMIN = "ADMIN",
  MODERATOR = "MODERATOR",
  USER = "USER",
}

export enum DeliveryStatus {
  REQUESTED = "REQUESTED",
  SCHEDULED = "SCHEDULED",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
}
